### ISSUE TITLE
Bug in set_spectrum

### ISSUE THREAD

**Issue by bened-wards** [g2v-optics/G2VPico#14]
Hi guys, playing around with the API and noticed a bug when trying to set a spectrum. Cannot set values to zero in current model due to if statement on line 449:

```
if channel and value:
    result_array[channel] = self.set_channel_value(channel=channel, value=value)
```

Propose change to below or something similar:
```
if channel and (value or value == 0):
    result_array[channel] = self.set_channel_value(channel=channel, value=value)
```

**Comment by chris-g2v** [comment]
Thank you @bened-wards for your feedback and solution. Much appreciated.
